//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FlyingPawn.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//

#pragma once

#include "FlyingEnemy.h"

class FlyingPawn : virtual public FlyingEnemy {
public:
    FlyingPawn();
    FlyingPawn(const Vector2& p_Position, const int p_iScreenWidth, const int p_iScreenHeight, 
        const char* p_pcTexturePath, const Vector2& p_Direction);

    void KamikazeAttack();

    void draw() override;
    void update() override;
    virtual void onClick() override {};
};
