//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticPawn.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_STATICPAWN_H)
#define _STATICPAWN_H

#include "Enemy.h"

class StaticPawn : public Enemy {
public:
	StaticPawn();
};

#endif  //_STATICPAWN_H
