//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bonus.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_BONUS_H)
#define _BONUS_H

#include "GraphicObjects.h"

class Bonus : public GraphicObjects {
public:
	Bonus(Vector2 p_Position);
	void ApplyBonus();
};

#endif  //_BONUS_H
