//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Boss.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_BOSS_H)
#define _BOSS_H

#include "FlyingEnemy.h"

class Boss : public FlyingEnemy {
public:
	void SpecialAttack();
};

#endif  //_BOSS_H
