//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Destroyable.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_DESTROYABLE_H)
#define _DESTROYABLE_H


__interface Destroyable {
public:
	bool getDestroyed();
	void setDestroyed(bool p_bDestroyed);
};

#endif  //_DESTROYABLE_H
