//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FlyinPawn.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_FLYINPAWN_H)
#define _FLYINPAWN_H

#include "FlyingEnemy.h"

class FlyinPawn : public FlyingEnemy {
public:
	void KamikazeAttack();
};

#endif  //_FLYINPAWN_H
