//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FlyingEnemy.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_FLYINGENEMY_H)
#define _FLYINGENEMY_H

#include "MovableObjects.h"
#include "Enemy.h"

class FlyingEnemy : public MovableObjects, public Enemy {
};

#endif  //_FLYINGENEMY_H
