//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GameManager.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_GAMEMANAGER_H)
#define _GAMEMANAGER_H


class GameManager {
public:
	static const int SCREEN_HEIGHT;
	static const int SCREEN_WIDTH;
	static const int NB_COLORS;
	static const int NB_SHOTS;
	void setup(char *p_pcBackgroundColorAsText);
	void runGame();
	void ManageBonusSpawning();
private:
	class Enemy {
	};
	Enemy **m_EnemiesArray;
	Color m_BackgroundColor;
	int m_iNbEnemybyColorArray;
	bool m_bGameOver;
	GameManager();
	void initEnemies();
	void manageButtonClick(Vector2 p_PlayerDirection);
	void drawVisualAids();
	bool checkClickOnEnemy();
	bool manageEnemies(int &nbColorDestroyed);
};

#endif  //_GAMEMANAGER_H
