//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GraphicObjects.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_GRAPHICOBJECTS_H)
#define _GRAPHICOBJECTS_H


class GraphicObjects {
public:
	void draw();
	Vector2 getCenterRotation();
	Vector2 getPosition();
	Texture2D getTexture();
	Rectangle getDestinationRectangle();
	Rectangle getSourceRectangle();
	void update();
	Rectangle getBoundingRectangle();
	float getOrientation();
private:
	Texture2D m_Texture;
	Vector2 m_CenterRotation;
	Rectangle m_SourceRectangle;
	Rectangle m_DestinationRectangle;
	Vector2 m_Position;
	float m_fOrientation;
	Rectangle m_BoundingRectangle;
};

#endif  //_GRAPHICOBJECTS_H
