//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HealingBonus.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_HEALINGBONUS_H)
#define _HEALINGBONUS_H

#include "Fillers.h"

class HealingBonus : public Fillers {
};

#endif  //_HEALINGBONUS_H
