//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MovableObjects.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_MOVABLEOBJECTS_H)
#define _MOVABLEOBJECTS_H

#include "GraphicObjects.h"

class MovableObjects : public GraphicObjects {
public:
	float getSpeed();
	Vector2 getDirection();
private:
	Vector2 m_Direction;
	float m_fSpeed;
};

#endif  //_MOVABLEOBJECTS_H
