//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Munition.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_MUNITION_H)
#define _MUNITION_H

#include "MovableObjects.h"
#include "Destroyable.h"

class Munition : public MovableObjects, public Destroyable {
public:
	bool getFired();
	Color getColor();
	void fire(Vector2 p_PlayerDirection);
	void draw();
	void reset();
	bool getDestroyed();
	void setDestroyed(bool p_bDestroyed);
private:
	int *m_Owner;
	bool m_bFired;
	Color m_Tint;
	float m_fScaleFactor;
	float m_fTargetWidth;
	float m_fTargetHeight;
	Munition(int p_Player);
	Munition(int p_Enemy);
	Munition();
};

#endif  //_MUNITION_H
