//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_PLAYER_H)
#define _PLAYER_H

#include "GraphicObjects.h"
#include "Destroyable.h"
#include "Shooter.h"

class Player : public GraphicObjects, public Destroyable, public Shooter {
public:
	float getOrientation();
	Vector2 update(int m_EnemiesArray, int *p_EnemyByColorArray);
	void turn();
	void shoot(Vector2 p_PlayerDirection);
	void ShootGrapnel();
	void AddBonusToSlot();
	bool getDestroyed();
	void setDestroyed(bool p_bDestroyed);
private:
	class Munition {
	};
	class Grapnnel {
	};
	Munition **m_ShotsArray;
	Grapnnel *m_pGrapnel;
	int m_iLifePoints;
	int m_iScore;
	Player(Vector2 p_Position, const int p_iScreenWidth, const int p_iScreenHeight, const char *p_pcTexturePath);
	~Player();
};

#endif  //_PLAYER_H
