//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Powerups.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_POWERUPS_H)
#define _POWERUPS_H

#include "Bonus.h"

class Powerups : public Bonus {
};

#endif  //_POWERUPS_H
