//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Quadrant.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_QUADRANT_H)
#define _QUADRANT_H


class Quadrant {
private:
	()
};

#endif  //_QUADRANT_H
