//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RammingShot.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_RAMMINGSHOT_H)
#define _RAMMINGSHOT_H

#include "Powerups.h"

class RammingShot : public Powerups {
};

#endif  //_RAMMINGSHOT_H
