//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Spawner.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_SPAWNER_H)
#define _SPAWNER_H


class Spawner {
public:
	void <<create>> Spawner();
	void ReadConfig();
	void CreatePawnArray();
	void SpawnRandomBonus(Vector2 p_Position);
	void DefineBonusToGenerate();
};

#endif  //_SPAWNER_H
