//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TripleShot.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_TRIPLESHOT_H)
#define _TRIPLESHOT_H

#include "Powerups.h"

class TripleShot : public Powerups {
};

#endif  //_TRIPLESHOT_H
