//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UpgradeBonus.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_UPGRADEBONUS_H)
#define _UPGRADEBONUS_H

#include "Fillers.h"

class UpgradeBonus : public Fillers {
};

#endif  //_UPGRADEBONUS_H
