//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bonus.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//

#include <raylib.h>
#include "Assets/Bonus.h"

Bonus::Bonus(Vector2 p_Position, const int p_iScreenWidth, const int p_iScreenHeight, const char* p_pcTexturePath)
    : GraphicObjects(p_Position, p_iScreenWidth, p_iScreenHeight, p_pcTexturePath)
{}

void Bonus::ApplyBonus() {
}

