//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bonus.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//

#pragma once
#include "Game/GraphicObjects.h"

class Bonus : public GraphicObjects {
public:
    Bonus(Vector2 p_Position, const int p_iScreenWidth, const int p_iScreenHeight, const char* p_pcTexturePath);
	void ApplyBonus();
};
