//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Fillers.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_FILLERS_H)
#define _FILLERS_H

#include "Bonus.h"

class Fillers : public Bonus {
};

#endif  //_FILLERS_H
