//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Grapnel.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Player/Grapnel.h"

Grapnel::Grapnel(Vector2 p_Position, const int p_iScreenWidth, const int p_iScreenHeight, const char* p_pcTexturePath)
    : MovableObjects(p_Position, p_iScreenWidth, p_iScreenHeight, p_pcTexturePath, {})
{
}

void Grapnel::TryGrabBonus(float p_fOrientation) {
}

void Grapnel::CalculateDirection() {
}

void Grapnel::Extends() {
}

void Grapnel::CatchBonus() {
}

