//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GraphicObjects.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//

#include <raylib.h>
#include <raymath.h>
#include "Game/GraphicObjects.h"
#include <Game/Utilities.h>

GraphicObjects::GraphicObjects( const Vector2& p_Position, 
                                const int p_iScreenWidth, 
                                const int p_iScreenHeight, 
                                const char* p_pcTexturePath)
    : m_Position{ p_Position }
    , m_Texture{ LoadTexture(p_pcTexturePath) }
    , m_fOrientation{ 0 }//Vector2Angle({}, m_Direction) }
    , m_CenterRotation{ m_Texture.height / 2.f, m_Texture.height / 2.f }
    , m_SourceRectangle{ 0,0,(float)m_Texture.width ,(float)m_Texture.height }
    , m_DestinationRectangle{ calculateDestinationRectangle(p_Position, m_CenterRotation, m_Texture, 1.f) }
    /*, m_DestinationRectangle{p_iScreenWidth / 2.f, p_iScreenHeight / 2.f,
                    (float)m_Texture.width , (float)m_Texture.height }

    m_DestRectangle{ getDestinationRectangle(m_Position, m_CenterRotation, m_BackTexture, 1.f) }*/
    , m_BoundingRectangle{ m_DestinationRectangle }
{

}


void GraphicObjects::draw() {
    //DrawRectanglePro(m_DestinationRectangle, m_CenterRotation, m_fOrientation, RED);
    DrawTexturePro(m_Texture, m_SourceRectangle, m_DestinationRectangle, m_CenterRotation, m_fOrientation, WHITE);
}


void GraphicObjects::update() {
}