//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MovableObjects.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include <raylib.h>
#include <raymath.h>
#include "Game/MovableObjects.h"


MovableObjects::MovableObjects()
    : MovableObjects({}, 0, 0, "", {})
{ }

MovableObjects::MovableObjects(const Vector2& p_Position, const int p_iScreenWidth, 
    const int p_iScreenHeight, const char* p_pcTexturePath,
    const Vector2& p_Direction)
    : GraphicObjects(p_Position, p_iScreenWidth, p_iScreenHeight, p_pcTexturePath)
    , m_Direction{ p_Direction }
    , m_fSpeed{2.f}
{ }