//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bonus.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Bonus.h"

Bonus::Bonus(Vector2 p_Position) {
}

void Bonus::ApplyBonus() {
}

