//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Drones.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Drones.h"

void Drones::ScanForEnemy() {
}

void Drones::OnEnemyInRange() {
}

