//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemy.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Enemy.h"

Texture Enemy::getBackTexture() {
}

Color Enemy::getTint() {
}

void Enemy::setTint(int p_iColor) {
}

void Enemy::setDestroyed(bool p_bDestroyed) {
}

bool Enemy::getDestroyed() {
}

void Enemy::Attack() {
}

bool Enemy::getDestroyed() {
}

void Enemy::setDestroyed(bool p_bDestroyed) {
}

Enemy::Enemy() {
}

Enemy::~Enemy() {
}


