//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FlyinPawn.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "FlyinPawn.h"

void FlyinPawn::KamikazeAttack() {
}

