//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GameManager.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "GameManager.h"

int GameManager::SCREEN_HEIGHT;

int GameManager::SCREEN_WIDTH;

int GameManager::NB_COLORS;

int GameManager::NB_SHOTS;

void GameManager::setup(char *p_pcBackgroundColorAsText) {
}

void GameManager::runGame() {
}

void GameManager::ManageBonusSpawning() {
}

GameManager::GameManager() {
}

void GameManager::initEnemies() {
}

void GameManager::manageButtonClick(Vector2 p_PlayerDirection) {
}

void GameManager::drawVisualAids() {
}

bool GameManager::checkClickOnEnemy() {
}

bool GameManager::manageEnemies(int &nbColorDestroyed) {
}


