//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GraphicObjects.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "GraphicObjects.h"

void GraphicObjects::draw() {
}


void GraphicObjects::update() {
}