//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Grapnel.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Grapnel.h"

void Grapnel::TryGrabBonus(float p_fOrientation) {
}

void Grapnel::CalculateDirection() {
}

void Grapnel::Extends() {
}

void Grapnel::CatchBonus() {
}

Grapnel::Grapnel() {
}

