//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MovableObjects.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "MovableObjects.h"

float MovableObjects::getSpeed() {
}

Vector2 MovableObjects::getDirection() {
}

