//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Munition.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Munition.h"

bool Munition::getFired() {
}

Color Munition::getColor() {
}

void Munition::fire(Vector2 p_PlayerDirection) {
}

void Munition::draw() {
}

void Munition::reset() {
}

bool Munition::getDestroyed() {
}

void Munition::setDestroyed(bool p_bDestroyed) {
}

Munition::Munition(int p_Player) {
}

Munition::Munition(int p_Enemy) {
}

Munition::Munition() {
}

