//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Player.h"

float Player::getOrientation() {
}

Vector2 Player::update(int m_EnemiesArray, int *p_EnemyByColorArray) {
}

void Player::turn() {
}

void Player::shoot(Vector2 p_PlayerDirection) {
}

void Player::ShootGrapnel() {
}

void Player::AddBonusToSlot() {
}

bool Player::getDestroyed() {
}

void Player::setDestroyed(bool p_bDestroyed) {
}

Player::Player(Vector2 p_Position, const int p_iScreenWidth, const int p_iScreenHeight, const char *p_pcTexturePath) {
}

Player::~Player() {
}



