//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Shield.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Shield.h"

void Shield::ReceiveImpact() {
}

void Shield::LevelUp() {
}

void Shield::FullRestore() {
}

void Shield::Restore(int p_iRestorePoints) {
}

Shield::Shield() {
}

