//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Spawner.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "Spawner.h"

void Spawner::<<create>> Spawner() {
}

void Spawner::ReadConfig() {
}

void Spawner::CreatePawnArray() {
}

void Spawner::SpawnRandomBonus(Vector2 p_Position) {
}

void Spawner::DefineBonusToGenerate() {
}

