//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StaticPawn.cpp
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#include "StaticPawn.h"

StaticPawn::StaticPawn() {
}

