//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GraphicObjects.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//

#pragma once
#include <raylib.h>
class GraphicObjects {
public:
    GraphicObjects(const Vector2& p_Position, const int p_iScreenWidth, 
        const int p_iScreenHeight, const char* p_pcTexturePath);
    virtual ~GraphicObjects() {};

    virtual void draw();
	virtual void update();
	virtual void onClick()=0;

    Vector2 getCenterRotation() { return m_CenterRotation; }
    Vector2 getPosition() { return m_Position; }
    Texture2D getTexture() { return m_Texture; }
    Rectangle getDestinationRectangle() { return m_DestinationRectangle; }
    Rectangle getSourceRectangle() { return m_SourceRectangle; }
    Rectangle getBoundingRectangle() { return m_BoundingRectangle; }
    float getOrientation() { return m_fOrientation; }

protected:
	Texture2D m_Texture;
	Vector2 m_CenterRotation;
	Rectangle m_SourceRectangle;
	Rectangle m_DestinationRectangle;
	Vector2 m_Position;
	float m_fOrientation;
	Rectangle m_BoundingRectangle;
};