//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MovableObjects.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#pragma once

#include "GraphicObjects.h"

class MovableObjects : virtual public GraphicObjects {
public:
    MovableObjects();
    MovableObjects(const Vector2& p_Position, const int p_iScreenWidth, const int p_iScreenHeight, const char* p_pcTexturePath, 
        const Vector2& p_Direction);

    float getSpeed() { return m_fSpeed; }
    Vector2 getDirection() { return m_Direction; }

protected:
	Vector2 m_Direction;
	float m_fSpeed;
};

