//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Shooter.h
//  @ Date : 25/11/2021
//  @ Author : 
//
//


#if !defined(_SHOOTER_H)
#define _SHOOTER_H


__interface Shooter {
};

#endif  //_SHOOTER_H
